services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_hospiscan
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3001:3001'
    depends_on:
      - mysql


  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

